name: checks default

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install
      - name: build prod project
        run: npm run build-only
      - name: run ts linter
        if: always()
        run: npm run type-check
      - name: run linter general
        if: always()
        run: npm run lint
      - name: run css linter
        if: always()
        run: npm run lint:scss
     
     